name: Test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: generate-image-metadata
        uses: docker/metadata-action@v3
        with:
          images: foo-bar
          flavor: |
            latest=false
          tags: |
            type=sha,prefix=,format=short
            type=ref,event=branch,prefix={{sha}}-
            type=ref,event=pr,prefix={{sha}}-
          labels: |
            org.opencontainers.image.source=internal
            org.opencontainers.image.url=https://plextrac.com
