name: Test

on:
  #workflow_dispatch:
  
  release:
    types:
      - created
      - edited
  
env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c1-7)
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the semver tag
        id: semver
        run: |
          echo "::set-output name=number::$(${{ env.GITHUB_REF }}##*/)"
      - name: Print output
        run: echo ${{ steps.semver.outputs.number }}
